server:
  port: 8007
spring:
  application:
    name: contact-service
  datasource:
    url: jdbc:mariadb://localhost:3306/micro_contact?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
  liquibase:
    change-log: classpath:db/changelog/db.changelog.master.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
info:
  application:
    name: contact admin
    description: talk user with admin about probelems.
    version: 1.0.0
